declaration:
    resource: "@DeclarationBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

template:
    resource: "@TemplateBundle/Resources/config/routing.yml"
    prefix:   /

billing:
    resource: "@BillingBundle/Resources/config/routing.yml"
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /

customer:
    resource: "@CustomerBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



