<?php

namespace BillingBundle\Repository;

/**
 * SalesDocumentDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesDocumentDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
