<?php

namespace BillingBundle\Repository;

/**
 * SalesDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
