<?php

namespace BillingBundle\Repository;

/**
 * SalesDocumentPayment
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesDocumentPayment extends \Doctrine\ORM\EntityRepository
{
}
