<?php

namespace BillingBundle\Repository;

/**
 * SalesDocumentProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesDocumentProductRepository extends \Doctrine\ORM\EntityRepository
{
}
