bank_operation_index:
    path:     /{id}
    defaults: { _controller: "BankBundle:Operation:index" }
    methods:  GET
bank_operation_new:
    path:     /{id}/new
    defaults: { _controller: "BankBundle:Operation:new" }
    methods:  [GET, POST]
bank_operation_edit:
    path:     /{id}/edit
    defaults: { _controller: "BankBundle:Operation:edit" }
    methods:  [GET, POST]
bank_operation_delete:
    path:     /{id}/delete
    defaults: { _controller: "BankBundle:Operation:delete" }
    methods:  [GET, POST]