bank_operation_index:
    path:     /{id}
    defaults: { _controller: "BankBundle:Operation:index" }
bank_operation_new:
    path:     /{id}/new
    defaults: { _controller: "BankBundle:Operation:new" }
bank_operation_edit:
    path:     /{id}/edit
    defaults: { _controller: "BankBundle:Operation:edit" }
bank_operation_delete:
    path:     /{id}/delete
    defaults: { _controller: "BankBundle:Operation:delete" }
bank_operation_pointed:
    path:     /{id}/pointed
    defaults: { _controller: "BankBundle:Operation:pointed" }
