bank_recurrence_new:
    path:     /new/{id}
    defaults: { _controller: "BankBundle:Recurrence:new" }
    methods:  [GET, POST]
bank_recurrence_edit:
    path:     /edit/{id}
    defaults: { _controller: "BankBundle:Recurrence:edit" }
    methods:  [GET, POST]
bank_recurrence_delete:
    path:     /delete/{id}
    defaults: { _controller: "BankBundle:Recurrence:delete" }
    methods:  [GET, POST]