<?php

namespace BankBundle\Repository;

/**
 * OperationTiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationTiersRepository extends \Doctrine\ORM\EntityRepository
{
}
