<?php

namespace BankBundle\Repository;

/**
 * OperationCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
